src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    use TimestampableEntity;
    use SoftDeleteableEntity;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotNull
     */

    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
    /**
     * @var string password before hashing
     * @ORM\Column(type="string")
     */
    private $plainPassword;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */

    private $firstName;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */
    private $lastName;
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $note;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postalCode;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $town;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Department", inversedBy="users")
     */
    private $department;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PayRate", mappedBy="user",cascade={"persist"})
     */
    private $payRates;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Position", inversedBy="users")
     */
    private $position;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\WorkStatus", mappedBy="user", orphanRemoval=true)
     */
    private $statuses;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Shift", mappedBy="user", orphanRemoval=true)
     */
    private $shifts;


    public function __construct()
    {
        $this->payRates = new ArrayCollection();
        $this->statuses = new ArrayCollection();
        $this->dutyRoosters = new ArrayCollection();
        $this->shifts = new ArrayCollection();

    }

    /**
     * @return mixed
     */
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }


    /**
     * @param mixed $plainPassword
     */
    public function setPlainPassword($plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): self
    {
        $this->town = $town;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        $department = $this->department;
        if (null === $department) {
            $department = new Department();
            $department->setName('Brak działu');
            return $department;
        }
        return $this->department;
    }

    public function setDepartment(?Department $department): self
    {
        $this->department = $department;

        return $this;
    }

    /**
     * @return Collection|PayRate[]
     */
    public function getPayRates(): Collection
    {
        return $this->payRates;
    }

    public function addPayRate(PayRate $payRate): self
    {
        if (!$this->payRates->contains($payRate)) {
            $this->payRates[] = $payRate;
            $payRate->setUser($this);
        }

        return $this;
    }

    public function removePayRate(PayRate $payRate): self
    {
        if ($this->payRates->contains($payRate)) {
            $this->payRates->removeElement($payRate);
            // set the owning side to null (unless already changed)
            if ($payRate->getUser() === $this) {
                $payRate->setUser(null);
            }
        }

        return $this;
    }

    public function getPosition(): ?Position
    {
       $position =  $this->position;
        if(null === $position){
            $position = new Position();
            $position->setName('Brak stanowiska');
            return $position;
        }

        return $this->position;
    }

    public function setPosition(?Position $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getFullName():string
    {
        return $this->getFirstName().' '. $this->getLastName();
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|WorkStatus[]
     */
    public function getStatuses(): Collection
    {
        return $this->statuses;
    }

    public function addStatus(WorkStatus $status): self
    {
        if (!$this->statuses->contains($status)) {
            $this->statuses[] = $status;
            $status->setUser($this);
        }

        return $this;
    }

    public function removeStatus(WorkStatus $status): self
    {
        if ($this->statuses->contains($status)) {
            $this->statuses->removeElement($status);
            // set the owning side to null (unless already changed)
            if ($status->getUser() === $this) {
                $status->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Shift[]
     */
    public function getShifts(): Collection
    {
        return $this->shifts;
    }

    public function addShift(Shift $shift): self
    {
        if (!$this->shifts->contains($shift)) {
            $this->shifts[] = $shift;
            $shift->setUser($this);
        }

        return $this;
    }

    public function removeShift(Shift $shift): self
    {
        if ($this->shifts->contains($shift)) {
            $this->shifts->removeElement($shift);
            // set the owning side to null (unless already changed)
            if ($shift->getUser() === $this) {
                $shift->setUser(null);
            }
        }

        return $this;
    }

}

src/Controller/DutyRoosterController.php
<?php

namespace App\Controller;

use App\Repository\UserRepository;
use App\Service\DateTimeService;
use App\Service\ShiftService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Contracts\Translation\TranslatorInterface;

class DutyRoosterController extends AbstractController
{
    /**
     * @var UserRepository
     */
    private $userRepository;
    /**
     * @var ShiftService
     */
    private $shiftService;
    /**
     * @var Security
     */
    private $security;
    /**
     * @var TranslatorInterface
     */
    private $translator;

    public function __construct(
        UserRepository $userRepository,
        ShiftService $shiftService,
        Security $security,
        TranslatorInterface $translator
    ) {
        $this->userRepository = $userRepository;
        $this->shiftService = $shiftService;
        $this->security = $security;
        $this->translator = $translator;
    }

    /**
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return JsonResponse
     * @throws \Exception
     * @Route("/duty_rooster/add",name="addRooster",methods={"POST"})
     */
    public function addRooster(Request $request, EntityManagerInterface $em, ShiftService $shiftService)
    {

        if ($request->isXmlHttpRequest()) {
            $timesheets = $request->request->get('timesheet');

            $now = new \DateTime('now');
            $now = $now->format('d-m-Y');
            $startDate = $timesheets[0]['dateFrom'];

            if(strtotime($now) > strtotime($startDate)){
                return new JsonResponse(['error' => 'Nie można dodać grafiku dla przeszłej daty'],Response::HTTP_ACCEPTED);
            }

            $shifts = $shiftService->createShiftFromTimesheets($timesheets);

            try {
                foreach ($shifts as $shift) {
                    $em->persist($shift);
                }
                $em->flush();
            } catch (\Exception $e) {
                throw $e;
            }


            return new JsonResponse(['data' => $timesheets]);
        }
        return new JsonResponse();
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     * @Route("/duty_rooster/{date}", name="duty_rooster",defaults={"date"=null})
     */
    public function index($date)
    {
        $users = $this->userRepository->findAll();

        if ($date == null) {
            $actualDate = new \DateTime();
        } else {
            $actualDate = DateTimeService::getDateFromDateString($date, null);
        }

        $monthDays = DateTimeService::getDaysInMonth($actualDate);
        $usersDto = $this->shiftService->getUsersDtoWithShiftsInMonth($users, $actualDate);
        return $this->render('duty_rooster/index.html.twig',
            ['monthDays' => $monthDays, 'users' => $users, 'usersDto' => $usersDto, 'actualDate' => $actualDate]);
    }

    /**
     * @param Request $request
     * @return JsonResponse
     * @throws \Exception
     * @Route("/duty_rooster/changeRoosterDate/{date}/{direction}",name="changeRoosterDate",methods={"GET"},defaults={"direction"=null})
     */
    public function changeRoosterDate($date, $direction)
    {
        $changedDate = DateTimeService::getDateFromDateString($date, $direction);

        return $this->redirectToRoute('duty_rooster', ['date' => $changedDate->format('d-m-Y')]);
    }

    /**
     * @param Request $request
     * @return JsonResponse
     * @throws \Exception
     * @Route("/duty_rooster/getMonthTimesheetForUser/{date}/{direction}",name="getMonthTimesheetForUser",methods={"GET"},defaults={"direction"=null})
     */
    public function getMonthTimesheetForUser(Request $request, ShiftService $shiftService)
    {
        $user = $this->security->getUser();

        $monthDays = DateTimeService::getDaysInMonth(\DateTime::createFromFormat("d-m-Y", $request->get('date')));

        $actualDate = DateTimeService::getDateFromDateString($request->get('date'), $request->get('direction'));

        $shiftsDto = $shiftService->createShiftDtoForUser($user, $actualDate);
        $shiftsView = $this->renderView('duty_rooster/timesheet.html.twig',
            ['shiftsDto' => $shiftsDto, 'monthDays' => $monthDays, 'actualDate' => $actualDate->format('d-m-Y')]);

        return new JsonResponse([$shiftsView]);
    }
}

templates/duty_rooster/dutyRooster_base.html.twig
{% extends 'base.html.twig' %}
{% block body_columns %}col-12{% endblock body_columns %}
  {% block navbar_links %}
              <li class="nav-item">
                  <a class="nav-link no-link" href="#">Grafik Pracy</a>
              </li>
                  <li class="nav-item" id="prev"  data-path=""><a href="{{ path('changeRoosterDate',{date: actualDate | date('d-m-Y'),direction:"prev"}) }}" class="nav-link"><i
                                  class="material-icons no-line-height" style="font-size:24px;color:#b8babe">keyboard_arrow_left</i></a>
              </li>
              <li class="nav-item">
                  <span id="dutyRoosterDate" data-date="{{ actualDate | date('d-m-Y') }}"class="nav-link disabled">{{ actualDate|date('F') | trans}} {{ actualDate |date('Y')}}</span>
              </li>
              <li class="nav-item" id="next" data-path="">
                  <a class="nav-link" href="{{ path('changeRoosterDate',{date: actualDate | date('d-m-Y'),direction:"next"}) }}"><i
                              class="material-icons no-line-height" style="font-size:24px;color:#b8babe">keyboard_arrow_right</i></a>
              </li>
              {% if is_granted('ROLE_ADMIN') %}
                  {% if "now"|date('m-Y') > actualDate | date('m-Y')%}
                      {% set disabled = true %}
                  {% else%}
                      {% set disabled = false %}
                  {%  endif %}
                  {% if disabled == true %}
                      <li class="nav-item"><a class="nav-link" href="#"><i class="material-icons no-line-height" style="font-size:24px;color:#b8babe;opacity:0.5">settings</i></a></li>
                  {% else %}
                      <li class="nav-item" id="addRooster"><a class="nav-link" data-toggle="tooltip" title="Dodaj grafik" data-placement="right" href="#">
                              <i class="material-icons no-line-height" style="font-size:24px;color:#b8babe">settings</i></a>
                      </li>
                  {% endif %}

              <form action="{{ path('duty_rooster', {'date': actualDate|date('d-m-Y')}) }}">
                  <button type="submit" class="btn btn-sm btn-light" id="restore" disabled>
                      Przywróć
                  </button>
              </form>

              <button class="btn btn-sm btn-light" id="publish" disabled>
                 Opublikuj
              </button>
              {% endif %}
          </ul>
      </div>
  {% endblock navbar_links %}
{% block modals %}

    {{ include('modals/roosterUserListModal.thml.twig') }}
    {{ include('modals/addDutyRoosterModal.html.twig') }}

{% endblock %}
{% block javascript %}
{{ parent() }}
<script src="{{ asset('js/dutyRooster.js') }}"></script>
<script src="{{ asset('js/dutyRoosterModal.js') }}"></script>


{% endblock %}

templates/duty_rooster/index.html.twig
{% extends 'duty_rooster/dutyRooster_base.html.twig' %}

{% block title %}Kreator grafików{% endblock %}
 {% block department %}{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-2 pr-0 pl-0" style="height: 91vh;overflow-x: scroll">
            <table class="table table-sm table-bordered text-center" style="table-layout: fixed;">
                <thead class="">
                <tr class="rooster-table-head">
                    <th scope="col">Osoba</th>
                </tr>
                </thead>
                <tbody class="rooster-users-table-body">
                {% for user in usersDto %}
                    <tr>
                        <td class=""
                            style="border-right:0px solid">
                            <div class="rooster-user-wrapper">
                                <p class="rooster-user">{{ user.fullName }}</p>
                                <p class="rooster-department">{{ user.department }}</p>
                                <p class="rooster-schedule">160/20</p>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-10 pl-0" style="overflow-x: auto;height: 91vh">
            <table class="table table-sm table-bordered" style="table-layout: fixed ">
                <thead class="thead-light">
                <tr class="rooster-table-head" widht="100%">
                    {% for date,value in monthDays %}
                        <th width="80px">{{ value['monthDay'] }} {{ value['day']|trans }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody class="rooster-table-body" data-path="{{ path('addRooster') }}">
                {% for user in usersDto %}
                    <tr data-user-id="{{ user.id }}">
                        {% for shift in user.shifts %}
                        <td>
                             {% set day = shift.weekday|trans %}
                            <div style=""class="rooster-wrapper" data-date="{{ shift.date }}" data-numericDay="{{ shift.weekDayNumber }}"
                                 value="{{ shift.weekDay|trans}}">
                                <div class="rooster-cell">
                                    {% if shift.timeFrom != null %}
                                    <span class="rooster-time">{{ shift.timeFrom }}-{{ shift.timeTo }}</span>
                                    {% endif %}
                                    {% if shift.numberOfHours != null %}
                                            <span class="rooster-time">{{ shift.numberOfHours }} godzin pracy</span>
                                    {% endif %}

                                    {% if shift.countTimeBeforeWork != null %}
                                        <span class="rooster-overtime">+nadgodziny</span>
                                    {% elseif shift.countTimeAfterWork != null %}
                                        <span class="rooster-overtime">+nadgodziny</span>
                                    {% elseif shift.overtimeDutyRooster != null %}
                                        <span class="rooster-overtime">Grafik nadgodz.</span>
                                    {% endif %}
                                </div>

                            </div>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    </div>
{% endblock %}

templates/duty_rooster/timesheet.html.twig
<h3 class="p-3">Twój grafik pracy</h3>
<div class="row calendar">
        <span class="js-calendar-arrow timesheet-prev-link" data-path="{{ path('getMonthTimesheetForUser',{date: actualDate | date('d-m-Y'),direction:"prev"}) }}"><a
                    href="#"
                    class="nav-link"><i
                        class="material-icons no-line-height"
                        style="font-size:24px;color:#b8babe">keyboard_arrow_left</i></a>
        </span>

    <span id="timesheet-date" data-date="{{ actualDate | date('d-m-Y') }}"
          class="nav-link disabled">{{ actualDate|date('F') | trans }} {{ actualDate |date('Y') }}</span>
    <span  class="js-calendar-arrow timesheet-next-link" data-path="{{ path('getMonthTimesheetForUser',{date: actualDate | date('d-m-Y'),direction:"next"}) }}">
            <a class="" href="#"><i
                        class="material-icons no-line-height"
                        style="font-size:24px;color:#b8babe">keyboard_arrow_right</i></a>
        </span>
</div>
<div class="col-10 p-0" style="overflow-x: auto;margin-left: 25px;">
    <table class="table table-sm table-bordered" style="table-layout: fixed ">
        <thead class="thead-light">
        <tr class="rooster-table-head">
            {% for date,value in monthDays %}
                <th width="80px">{{ value['monthDay'] }} {{ value['day']|trans }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody class="rooster-table-body">
        <tr>
            {% for shift in shiftsDto %}
            <td>
                {% set day = shift.weekday|trans %}
                <div style="" class="rooster-wrapper" data-date="{{ shift.date }}"
                     data-numericDay="{{ shift.weekDayNumber }}"
                     value="{{ shift.weekDay|trans }}">
                    <div class="rooster-cell">
                        {% if shift.timeFrom != null %}
                            <span class="rooster-time">{{ shift.timeFrom }}-{{ shift.timeTo }}</span>
                        {% endif %}
                        {% if shift.countTimeBeforeWork != null %}
                            <span class="rooster-overtime">+nadgodziny</span>
                        {% elseif shift.countTimeAfterWork != null %}
                            <span class="rooster-overtime">+nadgodziny</span>
                        {% elseif shift.overtimeDutyRooster != null %}
                            <span class="rooster-overtime">Grafik nadgodz.</span>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </td>
        </tr>
        </tbody>
    </table>
</div>